DROP TABLE IF EXISTS biblio;
CREATE TABLE biblio (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Titre TEXT NOT NULL,
    Auteur TEXT NOT NULL,
    Année TEXT NOT NULL
);
