DROP TABLE IF EXISTS livres;
CREATE TABLE livres (
    id_livres INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Titre TEXT NOT NULL,
    Auteur TEXT NOT NULL,
    Année TEXT NOT NULL,
    Quantité INTEGER NOT NULL
);

DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id_user INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Nom TEXT NOT NULL,
    Prenom TEXT NOT NULL,
    Mdp TEXT NOT NULL,
    Mail TEXT NOT NULL,
    Roles TEXT NOT NULL
);

DROP TABLE IF EXISTS emprunts;
CREATE TABLE emprunts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    id_user INTEGER NOT NULL,
    id_livres INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Date_emprunt TEXT NOT NULL,
    Date_rendu TEXT NOT NULL,
    Statut TEXT NOT NULL,
    FOREIGN KEY (id_livres) REFERENCES livres(id_livres),
    FOREIGN KEY (id_user) REFERENCES users(id_users)
);
